### ISSUE TITLE
Listener is not working when listener is disposed in dispose()

### ISSUE THREAD

**Issue by YAPPDEF** [adee42/flutter_keyboard_visibility#10]
This code is not working. As soon as I remove the disposing of the listener, it works fine.

Btw: is there a way to get the event immediately? Not it's delayed when the keyboard is popping up.

```
final keyboardListener = KeyboardVisibilityNotification();

@override
void initState() {
  super.initState();
  keyboardListener.addNewListener(
      onChange: (bool visible) {
        print('KEYBOARD: $visible');
      },
    );
}

@override
void dispose() {
  keyboardListener.dispose();
  super.dispose();
}
```

**Comment by adee42** [comment]
I tried to reproduce the bug but I had some strange results. I added an exception handler to the dispose function which might resolve the issue.
As a workaround I would suggest not to dispose of the listener but to unsubscribe:

```
final keyboardListener = KeyboardVisibilityNotification();
int _keyboardVisibilitySubscriberId;

@override
void initState() {
  super.initState();
  _keyboardVisibilitySubscriberId = keyboardListener.addNewListener(
      onChange: (bool visible) {
        print('KEYBOARD: $visible');
      },
    );
}

@override
void dispose() {
  keyboardListener.removeListener(_keyboardVisibilitySubscriberId);
  super.dispose();
}
````

Otherwise could you describe what exactly happens (why it doesn't work) and maybe send me a complete project to replicate the error?

I also changed the behavior of the plugin in ver. 0.5.2, the message should pop up immediately on iOS, on Android there is no system event for the keyboard popping up, it can only be determined by the size of the visible screen (which will always be a little delayed as a specific size of the screen has to be occupied by the system in order to be sure that it is the keyboard).

**Comment by YAPPDEF** [comment]
@adee42 thanks, this is what I did as well (removeListener).

What happens: The onChange is not triggered anymore. So if I add the listener.dispose(), no event is fired anymore in the onChange function. Makes no sense to me, as the dispose is called after using it 😄 

Hmm, ok. Maybe it's only in release mode - I'll check.
I switched to this plugin as the viewInsets.bottom are not working anymore with the newest stable flutter version (`v1.2.1`). Are you using that or something else for Android?

**Comment by droidpl** [comment]
I have the same issue with the dispose function. Also did the same workaround, but I get a stacktrace when the dispose is called after an onchange subscription. This is the trace:

`══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown while finalizing the widget tree:
flutter: Invalid argument (onError): Error handler must accept one Object or one Object and a StackTrace as
flutter: arguments, and return a a valid result: Closure: () => Null
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      KeyboardVisibilityNotification.dispose (package:keyboard_visibility/keyboard_visibility.dart:88:48)`

The code is the same as its described in the issue, an onchange subscription + dispose on a stateful widget.

**Comment by adee42** [comment]
Fixed in ver. 0.5.3
